### ISSUE TITLE
Xiaomi sensors not available

### ISSUE THREAD

**Issue by aytec** [home-assistant/hassio-addons#1142]
All of my Xiaomi Sensors show that the Entity open/close is not available. In Phoscon i can see if open or close, but in home assistant (newest release 0.106.0) the only entity i see is battery status.

I have this problem since yesterday, and even a reboot didnt change anything

**Comment by Fulch** [comment]
I have this same problem since update to 0.106.0 for 3 of my Xiaomi sensors. The motion sensor is always ok but the two window sensors and one vibration sensor show as unavailable but the battery status is available for all of them.
Sometimes they will return if I choose update from the deconz integration page but not always. Have just updated deconz to 5.3 and restarted HA but still the same sensors are listed as unavailable.

Everything is visible from  Phoscon and the VNC interface at all times when this happens.

**Comment by D3nnisd** [comment]
This is going to be fixed in https://github.com/home-assistant/home-assistant/pull/32274
