### ISSUE TITLE
Phoscon GW at ip 172.30.xx.xx-, while HA exist at 192.168.xx.xx

### ISSUE THREAD

**Issue by bramv101** [home-assistant/hassio-addons#1183]
Running HassOS 3.12, installed deconz as explained, dongle is coming thorugh without problem, devices are coming through without a problem.
However when launching web UI, i get GW with 192.168.xx ip, once logged in it shows top right an ip with 172.30.xx.xx. in itself not a problem yet when trying to connect NodeRed, i get problems.
[](https://github.com/andreypopov/node-red-contrib-deconz)
I go in the the gateway and do authenticate app for 60 seconds, yet NodeRed refuses to connect.
My bet something funky is going on with those ip adresses

**Comment by frenck** [comment]
The listed IP address is correct and is not an issue. It is the IP the add-on has on the internal docker network. From the Phoscon perspective, it is the interface it is using.

For Node-RED this isn't part if an issue either, since Node-RED is on the same Docker network and thus, able to access that IP as well.
