### ISSUE TITLE
MariaDB: Fails silently

### ISSUE THREAD

**Issue by fabaff** [home-assistant/hassio-addons#1193]
If one doesn't read the docs and starts the Addon with the default configuration then the Addon fails silently at first glance. From an user perspective/experience point of view is this not optional, especially as this is targeting users which are not familiar with the inner workings.

The default config doesn't pass the validation

```text
databases:
  - homeassistant
logins:
  - username: homeassistant
    password: null
rights:
  - username: homeassistant
    database: homeassistant
```

My suggestion is to not only log the issue in the system's log but also in the Addon's log. Thought?

**Comment by frenck** [comment]
Not quite sure... so, quite possibly the frontend is already able to determine this? And thus maybe even possible to disable the start button with a message?

Just thinking out loud as well now. However, for the near future, a UI would be created to handle the options (instead of YAML). The UI schemas have recently been added to the Supervisor API.
