### ISSUE TITLE
Addon Let's Encrypt - Cloudflare DNS Restricted API token issues

### ISSUE THREAD

**Issue by dstretch** [home-assistant/hassio-addons#1221]
Hi,

When trying to set up the Let's Encrypt addon with Cloudflare DNS challenge I get this in the logs:

```
[12:33:21] INFO: Selected DNS Provider: dns-cloudflare
[12:33:21] INFO: Use propagation seconds: 60
[12:33:22] WARNING: Use CloudFlare global key (not recommended!)
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-cloudflare, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for <MyDomainNameHere>
Cleaning up challenges
Error determining zone_id: 6003 Invalid request headers. Please confirm that you have supplied valid Cloudflare API credentials. (Did you copy your entire API token/key? To use Cloudflare tokens, you'll need the python package cloudflare>=2.3.1. This certbot is running cloudflare 2.6.3)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
```

I'm using a restricted API token for Cloudflare as recommended, with the following permissions:

`All zones - Zone:Read, DNS:Edit`

I was surprised to see the log mention it was using a global key, even though I omitted the `cloudflare_email` parameter which I believe is what triggers it to be global or not:

`[12:33:22] WARNING: Use CloudFlare global key (not recommended!)`

My config:

```
email: <MyEmailAddress>
domains:
  - <MyDomainName>
certfile: fullchain.pem
keyfile: privkey.pem
challenge: dns
dns:
  provider: dns-cloudflare
  cloudflare_api_key: <MyAPIToken>
```

Have I done something stupid, or are others experiencing this too?

**Comment by rpbx** [comment]
I am having the same issue.

**Comment by jimmyeao** [comment]
I cant get the add on to even start with Cloudflare DNS, have tried both private and global API keys

**Comment by lunds** [comment]
I just went through setup today and struggled a little as well (my fault for not reading instructions to the letter).

To configure using the Cloudflare API Token, you need to use "cloudflare_api_token" instead of "cloudflare_api_key", and also set "cloudflare_email". The email is required to authenticate against the Cloudflare API.

Also ensure you have set the following permissions for the token in the Cloudflare dashboard:
Zone-Zone: Edit
Zone-DNS:Edit

Lastly (and this is what I missed when setting it up):
Under "Zone Resources" you must allow (include) "All zones". When I restricted access to only a single zone, I got the following error: 
Unable to determine zone_id for <domain> using zone names: ['<domain>', '<TLD>']. Please confirm that the domain name has been entered correctly and is already associated with the supplied Cloudflare account. The error from Cloudflare was: 0 Actor 'com.cloudflare.api.token.<guid>' requires permission 'com.cloudflare.api.account.zone.list' to list zones.
Allowing all Zones resolves this error.

Hope this helps :-)

**Comment by mroovers0904** [comment]
@lunds Huge thanks for your comment as that was what I needed to resolve my configuration. This is how I've set up successfully:

Config in Let's encrypt add-on:
email: my email address
domains:
  - '*.mydomain.com'
certfile: fullchain.pem
keyfile: privkey.pem
challenge: dns
dns:
  provider: dns-cloudflare
  cloudflare_api_token: this is the token I specifically created for Zone-Zone:Edit and Zone-DNS:Edit and I included all zones as you selected.

Cloudflare config:
I created a TXT DNS record with name _acme-challenge and contents: _acme-challenge.mydomain.com. on Cloudflare to respond to the challenge and that did the trick.

**Comment by pergolafabio** [comment]
Struggling with this too , created that new token  , with new permissions : Zone-Zone:Edit and Zone-DNS:Edit

used my account email in the yaml config, but still error 6003
als tried creating that txt file witj acme challenge

didnt help either

what could be wrong?

**Comment by pergolafabio** [comment]
this is my config:

```
certfile: fullchain-cloudflare.pem
challenge: dns
dns:
  provider: dns-cloudflare
  cloudflare_email: cccc@gmail.com
  cloudflare_api_key: xxxx
domains:
  - www.xxx.com
email: ccccc@gmail.com
keyfile: privkey-cloudflare.pem
```

**Comment by pergolafabio** [comment]
omg, needed to use cloudflare_api_token  !! instead of key
