### ISSUE TITLE
Feature request: Addon MariaDB support of external USB storage media

### ISSUE THREAD

**Issue by quarcko** [home-assistant/hassio-addons#1223]
So, story goes like this: After 2nd uSD card failed (later confirmer in PC is full of bad sectors)
uSD's that failed where 32GB Sandisk EXTREME PRO ones.
(offtopic, now i changed to Panasonic pSLC semi-industrial with 20k erase/program cycles
but i still dont want to kill it too soon.)
so i started to think it is time to analyze situation. (i'm on pure hassio with hassos and etc.)
Glances addon showed that MariaDB addon generated a hell of disk IOW/s and i need majority
of that data for later processing so "disable them in recorder" is not an option for me. i already disabled there what i can.

So Glances show a regular IOW/s of about 0.5 - 2Mb/s for this addon. SO with such a high IOW,
it is even laughable to disabling any logging (of other addons and HA) to spare uSD card... 

So i gathered all the information i could find on the internet about external storage,
and created this proof of concept:
https://github.com/quarcko/MariaDB-USB-Hass.io-Add-On

It works, with EXT4 formatted USB3.0 thumb drive put into raspberry 4 USB 3.0 port.
drive is detected as /dev/sda1, and with modified addon it mounts and writes there.

All the IOW from this addon is now in Glances on sda1.
mmcblk still receiving some 1-40Kb randomly (even with all addons shut down, so probably
HASSOS or docker doing something which i can't further minimise).

Question:
Can these modification be added to this addon as an user configurable options
to use external USB thumb drive for data offloading?

P.S. I dont want external device with DB, as raspberry pi 4 with 4GB of RAM is what i bought it for.
to handle all the stuff alone and not depend on network devices to operate.
Just the uSD is weak point of this device, but as i proved damage can be minimised with using external flash drive (or HDD or SSD or whatever else).

**Comment by frenck** [comment]
You POC works, because:

<https://github.com/quarcko/MariaDB-USB-Hass.io-Add-On/blob/master/mariadb/config.json#L31>

However, this is a static configuration that does only work for a system that has that (as you concluded already).

This should not be part of add-on configuration, but part of the system setup. There is already some work done on offloading data to other partitions or drives. However, this is not done yet.

Since this is should not be an add-on option, I'm going ahead and close this specific issue (well feature request actually).

👍
