### ISSUE TITLE
Custom add-on repositories missing from the UI

### ISSUE THREAD

**Issue by bmcclure** [home-assistant/hassio-addons#1279]
I am no longer seeing my custom repositories showing up at the top of the Add-on Store, nor the box to add a new custom repository URL.

I am not sure exactly when this happened, possibly with a recent Home Assistant update through the UI. It is still showing the community add-ons that I've added previously, but it just won't show me the actual repositories at the top or let me add any more.

There are some JS console errors on the page that may be related:

`Uncaught (in promise) InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': A version change transaction is running.`

And lots of icon-related errors:

`Failed to load resource: the server responded with a status of 404 ()`
`Uncaught (in promise) SyntaxError: Unexpected token : in JSON at position 3`

**Comment by trikidiki** [comment]
I've been banging my head against the same problem for a few hours.

Running Home Assistant 0.109.6 on Proxmox. Also have the same problem on 0.109.3 running on a Pi4.

I only had a couple of errors in the log and they were apparently due to something in Node-Red.

If I can give any more information to help resolve this , please ask.

Thanks.

**Comment by ludeeus** [comment]
duplicate  of https://github.com/home-assistant/frontend/issues/5807
