### ISSUE TITLE
Deleted config

### ISSUE THREAD

**Issue by AmazedWolf900** [home-assistant/hassio-addons#1320]
This fu*king piece of shit just deleted my whole configuration folder.

**Comment by frenck** [comment]
Hi there @AmazedWolf900.

That doesn't sound good and frustrating. However, not totally clear what you are referring to.

Furthermore, please note we have a Code of Conduct that is in place to maintain a certain level of friendliness in our community. The language used in your issue is thus not accepted and can result in a ban.

Everybody is happy to help in general.
