### ISSUE TITLE
Conbee II, deConz, Phoscon suddenly stop working

### ISSUE THREAD

**Issue by GubbDump** [home-assistant/hassio-addons#1382]
Recently I had 5 SmartThings light bulbs and 1 SmartThings multi-purpose sensor all synced to a Conbee II running on Home Assistant with the deConz add-in.  Everything was working great up until this morning, opened the Home Assistant mobile app and noticed all my dimmers were "Currently Unavailable".  I logged into my Home Assistant, went to the deConz integration and noticed all my lights were "Unreachable".  Launched the deConz add-in and my normal password was not working, tried to reset password and it wouldnt let me.  I then disabled the integration, uninstalled the addon and tried to set everything up again.  Upon trying to sync the devices back to the Conbee II I am unsuccessful, nothing is being discovered anymore and I can no longer sync devices.

Has anyone seen anything like this before?  I have tried many troubleshooting steps, been working on this for about 3 hours and I cant seem to get it to work anymore.

Any help is appreciated.  Let me know if more information is needed.

Thanks!

**Comment by sebastien-k** [comment]
Exactly same issue here.

**Comment by Lunatixz** [comment]
I'm having issues as well after updating to HassOS v4.10.. The log indicates ERROR: Problem connecting to server (get for https://acme-v02.api.letsencrypt.org/directory; curl returned with 7)

**Comment by thecem** [comment]
@GubbDump first you have to check if Conbee is in deconz recognized:
- If firmware is not unknown or 000000000 it is connected:
![grafik](https://user-images.githubusercontent.com/46648579/85203478-7447d480-b30e-11ea-8d05-4f610e522f8d.png)
- If not check if Supervisor knows your HW:
![grafik](https://user-images.githubusercontent.com/46648579/85203535-bcff8d80-b30e-11ea-9b82-77f0348c4e5e.png)
![grafik](https://user-images.githubusercontent.com/46648579/85203583-136ccc00-b30f-11ea-9853-6be11c511b3a.png)

- if not reboot the whole system, since your device (conbee) is not recogniezed by supervisor.

to avoid problems with ttyACMx use as device id for deconz config the UNIQUE deviceid: 

`/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1234567-if00`
