### ISSUE TITLE
ozw-admin Screen Size

### ISSUE THREAD

**Issue by Veldkornet** [home-assistant/hassio-addons#1417]
Is it at all possible to get the ozw-admin screen to "file the screen" or something to that effect?
For me at least, it's all squished into a small square with mostly just scroll bars everywhere

**Comment by frenck** [comment]
Since it uses a VNC type of connection, automatic adjusting won't be possible.

However, I did try to add a setting/option to allow for users to set their own screen size. Unfortunately, the OZW Admin application didn't handle this well. Hence it is currently set to the resolution that works.

Hopefully, we can improve on this in the near future.

**Comment by gilperme** [comment]
+1 Vote for this option. Thanks @frenck for all the work on this add-on.

**Comment by bruxy70** [comment]
Just to add a screenshot: 
![image](https://user-images.githubusercontent.com/44951610/92281450-edad9700-eefb-11ea-8a5a-1864db5a132e.png)
