### ISSUE TITLE
Update to Deconz 2.05.78

### ISSUE THREAD

**Issue by wovka88** [home-assistant/hassio-addons#1428]
Is an update to version 2.05.78 planned? 

https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_78

Or is it possible to perform an update yourself?

**Comment by dhartmann1979** [comment]
It would interest me too

**Comment by renedis** [comment]
I have a lumi.plug.mmeu01 (Xiaomi EU socket) that works from 2.05.76. Zo basicly I'm hoping for an update too.

**Comment by cvladan** [comment]
We are already 3 versions behind original deCONZ REST?

I don't understand the reasoning on "downgrading due problems".
Because, I have a lot of problems because of downgrading via update - notably by not supporting important devices!

**Comment by cvladan** [comment]
> 
> 
> I have a lumi.plug.mmeu01 (Xiaomi EU socket) that works from 2.05.76. So basicly I'm hoping for an update too.

There was an update, but then they downgraded?

**Comment by stickpin** [comment]
Hi All,

There were many complaints about a 2.05.76+, that's why it's rolled back to 2.05.75, see [deCONZ change log](https://github.com/home-assistant/hassio-addons/blob/master/deconz/CHANGELOG.md).

Currently, I am running v2.05.78 using local addon installation for me it's working stable except some issues related to IKEA bulbs and new lighting refactoring introduced in v2.05.76.

I can push update but I am afraid it may create a problems to people once again.

**Comment by renedis** [comment]
Thanks for the update. I've had zero issues with version 2.05.76+ before and I have 18 IKEA tradfi bulbs.
