### ISSUE TITLE
Aeotec Smart Switches not reporting back to HA

### ISSUE THREAD

**Issue by gazelle-hub** [home-assistant/hassio-addons#1453]
I've got a couple of Aeotec Smart Switches that I had been using without any issues with the old ZWave integration.

Since switching to the new OpenZwave Integration with the OpenZWave Add-on I've been finding that the switches aren't always reporting back to HA.

This means sometimes they aren't reporting back their on/off status and sometimes as well they don't report back their usage statistics.

If I open up the OpenZWave add-on I can see the correct on/off status and see that the W's etc are changing but these aren't being shown in HA.

**Comment by marcelveldt** [comment]
Please report this issue to the [core repo](https://github.com/home-assistant/core/issues?q=label%3A%22integration%3A+ozw%22) as it's related to the ozw integration and not the addon.

That said, when you do submit the issue, would it be possible to do some debugging at forehand ?
Install the MQTT Explorer tool and connect it to your MQTT daemon. Explore the OpenZWave topic and browse into the node for the smart switch. Expand the correct CommandClass and Value until you find the value that belongs to the Power meter sensor. Check if this value does actually change correctly. HomeAssistant should use that value. If that value is also incorrect, the issue is the OZW Daemon itself.

Thanks!

**Comment by TomBrandt** [comment]
After update to 5.0 DZ15S-1BZ Decora Smart Switch
by Leviton causes constant events and log are streaming through Constantly. I couldn't capture it to describe. Also switched were uncontrollable in HA. restored back to 4.4 ok now Running VMBox Intel Nuc. HA 112.4 Supervisor 228 host Hassos 4.11

**Comment by gazelle-hub** [comment]
Happy to do that.

Just FYI, I've done this testing and had two different results.

Switch status - doesn't seem to change through the MQTT Explorer even though the switch is turning OFF and ON. Status in HA just continues to say ON even though it is OFF.
Power usage (Watts) - does seem to change through the MQTT Explorer but is not updated in HA.

**Comment by MartinHjelmare** [comment]
I'll close here since this is not a problem with the add-on, as already said above.
