### ISSUE TITLE
Deconz dont work

### ISSUE THREAD

**Issue by Kenneth198** [home-assistant/hassio-addons#1543]
## The problem
New install of conbee 2. 

## Environment
Hassio on docker synology

- Add-on with the issue: deconz
- Add-on release with the issue: 
- Last working add-on release (if known): newest
- Operating environment (OS/Supervised): 

## Problem-relevant configuration

```yaml

```

## Traceback/Error

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] firmware.sh: executing... 
/usr/bin/GCFFlasher_internal.bin: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
[19:26:00] INFO: 
[cont-init.d] firmware.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] novnc.sh: executing... 
[cont-init.d] novnc.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:26:02] INFO: Websockify waiting for VNC to start
[17:26:02] INFO: Starting udevd...
[17:26:02] INFO: Running the deCONZ OTA updater...
[17:26:02] INFO: Running the OSRAM LEdvance OTA updater...
[17:26:02] INFO: Running the IKEA OTA updater...
[19:26:02] WARNING: Your direct VNC access is not protected!
[19:26:02] INFO: Starting VNC server (local/no)...
[19:26:04] INFO: Starting websockify...
[19:26:07] INFO: deCONZ waiting for VNC to start
[19:26:07] INFO: Starting the deCONZ gateway...

deCONZ: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by pedolsky** [comment]
Same here.

**Comment by fredrike** [comment]
The problem is a compatibility issue between the libQt5Core shared library and the running kernel. The Synology system where deconz doesn't work is running a kernel version older than 3.17.

There is a workaround to strip the `.note.ABI-tag` ELF section from the shared library but as Synology isn't supported I don't think this will happen. I will fork the addons-repo and build a Synology compatible version @ https://github.com/fredrike/hassio-addons/tree/master/deconz. 

Short discussion here: https://community.home-assistant.io/t/hass-io-on-synology-dsm-native-package/125559/952?u=fredrike

**Comment by CaTbOx59** [comment]
Hello fredrike
First thanks you for your great job. Appriciate really😉
When do you think you can do this add-on? Is there a way to test now? "The strip tool is probably not included in your Docker container. You may need to install the binutils package"
what is binutils package?

**Comment by fredrike** [comment]
> When do you think you can do this add-on? Is there a way to test now? 

Yes there is a way.. 
https://community.home-assistant.io/t/hass-io-on-synology-dsm-native-package/125559/953?u=fredrike

**Comment by frenck** [comment]
This issue is caused by running an unsupported and incompatible system.

I would highly recommend looking for a different solution to run Home Assistant, as your problems will get worse over time. The offered community solution above may work for now, but stripping out ABI tags from the binaries is asking for problems as well (they are in there for a reason).
