### ISSUE TITLE
Let's Encrypt addon fails tostart

### ISSUE THREAD

**Issue by masarliev** [home-assistant/hassio-addons#281]
I am not able to update certificate because addon won't start. This is in syslog 

18-04-14 07:53:03 INFO (SyncWorker_10) [hassio.docker.interface] Clean homeassistant/armhf-addon-letsencrypt docker application
18-04-14 07:53:04 ERROR (SyncWorker_10) [hassio.docker] Can't start addon_core_letsencrypt: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_core_letsencrypt (f02325c6e24d436c91fd3535941f0f8d032cc9bdd81b26f972cc60a85ffe724d): Bind for 0.0.0.0:80 failed: port is already allocated")

**Comment by frenck** [comment]
@masarliev Thanks for you issue, nevertheless, the error message is pretty clear on the issue.

`Bind for 0.0.0.0:80 failed: port is already allocated`

The Let's Encrypt addon wants to open a port to the outside world (in this case) port 80. This issue is, that this port is already in use by something else. Maybe another add-on?

**Comment by frenck** [comment]
That is correct. LE will try to verify by contacting your instance over port 80.

You have 2 options:
1. Shutdown NGinx temporarily, start LE, wait for it to finish, start NGinx again.
1. Consider not to use port 80 on the NGinx addon (since you will be using SSL right?). This can be done by leaving the port mapping field of port 80 on the NGinx add-on empty.

**Comment by masarliev** [comment]
Thank you. Removing 80 port configuration from nginx fixed it and certificate is renewed successful.
