### ISSUE TITLE
New installation of hass.io missing repository 

### ISSUE THREAD

**Issue by wja731** [home-assistant/hassio-addons#303]
Hello!
I’ve tried reimaging my SD card multiple times with the lastest hassio release. Still no luck though, the only repository that displays is the Community Hassio Addons(https://github.com/hassio-addons/repository). Everytime I try to add this repository to my addon store I get this error:
18-05-12 15:44:22 ERROR (MainThread) [hassio.addons] Can't load from repository https://github.com/home-assistant/hassio-addons
18-05-12 15:44:22 INFO (MainThread) [hassio.addons] Load addons: 14 all - 0 new - 0 remove.
Please help, I want to use letsencrypt on my setup. Thanks, Will.

**Comment by iam9827** [comment]
I'm running into a similar issue, in which this repository fails to be cloned and therefor won't show up in the addon store for a fresh hassio install on a PI3:
18-05-22 00:00:10 ERROR (MainThread) [hassio.addons.git] Can't clone https://github.com/home-assistant/hassio-addons repo: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --recursive -v https://github.com/home-assistant/hassio-addons /data/addons/core
  stderr: 'Cloning into '/data/addons/core'...
POST git-upload-pack (177 bytes)
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 110
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
'.
18-05-22 00:00:10 ERROR (MainThread) [hassio.addons] Can't load from repository core

**Comment by Au8ust** [comment]
I have the same issue, is there any solutions? I already flashed the .bz2 file.

**Comment by pvizeli** [comment]
That is with ResinOS?

If I google this error message, I read that it could be a problem with Internet/Firewall. Anyway, I add a function to cleanup wrong repository and it will retry it on next boot.

Can someone test if that also a problem with HassOS ? https://github.com/home-assistant/hassos/releases

**Comment by Au8ust** [comment]
I reflash the ResinOS and the issue fixed

**Comment by michaelkuty** [comment]
I install hassio using this command `curl -sL https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install | bash -s -- -m raspberrypi` and I have same issue, in default I have installed https://github.com/hassio-addons/repository but I cannot install this repository, most errors are same `fatal: index-pack failed` and if pass then this error is raised `Can't read repository information from /data/addons/git/13c83a10/repository.json`
