### ISSUE TITLE
Configurator missing options

### ISSUE THREAD

**Issue by cbrherms** [home-assistant/hassio-addons#306]
Been trying to set Configurator up behind an Nginx proxy and need to modify the HASS_API value.
This can't be set via the addon config, is this something that can be changed?

**Comment by danielperna84** [comment]
For the hass.io version this can not be changed. It is hardcoded to `http://hassio/homeassistant/api/` since that's where hass.io is always reachable from the configurator. The API usually is only used internally for basic functionality. So there's no need to change it. Only the newer event observer connects directly to the API. But for that there's an input field where you can manually specify the API url.

**Comment by cbrherms** [comment]
I'd mis-diagnosed my issue. Turned out to be something else on the nginx side related to using the same domain name. Changing to a subdomain fixed the issue
