### ISSUE TITLE
Remove or improve Configurator's 'sesame' option

### ISSUE THREAD

**Issue by fabaff** [home-assistant/hassio-addons#314]
> - **sesame** (*Optional*): Secret token to dynamically allow access from the IP the request originates from. Open your bookmark https://hassio.yourdomain.com:8123/somesecretnobodycanguess while `allowed_networks` is set to `[]` and boom! Open Sesame! You can use the _Network status_ menu to revoke IP addresses for which access has been granted.

From a security point of view is this a pretty high risk. The token can be anything, as far as I can tell, which make it vulnerable for enumerations and simple guessing. The token is part of the request and will be visible in logs. It looks also like that we are facing a similar issue as with [#14345](https://github.com/home-assistant/home-assistant/issues/14345) here.

**Comment by danielperna84** [comment]
I think having the sesame-option is far less insecure than having to allow access from 0.0.0.0, which otherwise needs to be done for people who connect _externally_. So everybody with SSL who doesn't have a local DNS routing internally instead will just be protected by credentials. Attackers can start cracking the credentials right away. With the sesame it's credentials plus the token, with the requirement to brute force the token before you can even brute force the credentials.

From my point of view the sesame is about the same as having hass allow from 0.0.0.0 along with a strong API_KEY. A difference worth mentioning: attackers scanning random IPs will always get a 420 (policy not fulfilled) error. They would have to know that they are attacking the configurator with activated sesame to even think of brute forcing the sesame token.

**Comment by danielperna84** [comment]
[This](https://github.com/danielperna84/hass-configurator/pull/101) will allow to use a TOTP based sesame token instead of a static one. 6 digits provide much less entropy, but since these tokens are only valid for 30 seconds this seems fairly secure to me and makes brute forcing hard.
