### ISSUE TITLE
mosquitto runs as root?

### ISSUE THREAD

**Issue by freaky-m0** [home-assistant/hassio-addons#394]
After the first start of mosquitto this is in the log:

`Warning: Mosquitto should not be run as root/administrator.`

Why is it running as root? Or is this just a wrong message?

**Comment by freaky-m0** [comment]
No one? No reason? Sure a container should be sandboxed, but this is not a good practice. The principle of least privilege is the better choice.

**Comment by pvizeli** [comment]
We use AppArmor to protect the system. Only AppArmor can protect a system efficient with exploits. A user can also become root rights.

Anyway. It is simple to say some things but you need see that in context over the hole system. Actual it's not possible to use docker with system user over the hole context and different OS they we support.

**Comment by freaky-m0** [comment]
If you have a reason for doing this, thats okay. I wanted to know if there is any reason for this or if it's just an issue. 

So you say the mosquitto process inside the container needs to run as root because of the multiplatform support from hass.io?

**Comment by pvizeli** [comment]
I think it should be possible to add a option like `user_context: bool` with docker-ce > 18.x and allow to run a add-on in user context.

But we need care about:
- The solution can't break exists installation
- We need to be able to snapshot/restore the data on any kind of Linux based system
- The supervisor have no privileged or any other special rights
- Need also support embedded linux systems with RO root filesystems

Actual that have no prio for me, because we use docker and AppArmor. There are more important things to do. But I'm every time happy to see new contributors ;)
