### ISSUE TITLE
Anonymous login not working in MQTT addon v3

### ISSUE THREAD

**Issue by wroadd** [home-assistant/hassio-addons#446]
After upgrade MQTT addon to v3 and Hassio to 0.81.6, the anonymous login is not working even if I change the "anonymous" : false to true.

**Comment by wroadd** [comment]
There is some error report in HA forum: 
https://community.home-assistant.io/t/mosquito-mqtt-update-v3-broke-my-hassio/76991/51

**Comment by SiliconAvatar** [comment]
Same issue here.

I have numerous MQTT devices, all on a segregated internal network. I do not want to have the MQTT server be password protected or governed by an access control list of any kind.

After this update, setting "anonymous" : true has no effect, and devices seem to REQUIRE a username/pass to be in the ACL before it allows access to the broker.

**Comment by pvizeli** [comment]
ACL are currently by pass. I have no issue here with anonymous. Do you have save the config and press restart after the change on the add-on?

**Comment by SiliconAvatar** [comment]
> ACL are currently by pass. I have no issue here with anonymous. Do you have save the config and press restart after the change on the add-on?

Yes.
My configuration is:
>"logins": [],
>"anonymous": true,

I've restarted the add-on plenty of times and also have since upgraded to v4.
And still I get these errors:

>1541828382: New connection from 192.168.1.220 on port 1883.
>[ERROR] Auth error with DVES_USER
>1541828382: Socket error on client <unknown>, disconnecting.

I'm sure the client might be trying to say it has a user, but I don't care, and neither should the broker. In version 2 this was simply not an issue. I did not have any ACL defined, and anonymous was set to true and it "just worked". This is all in an internal segregated network, I do not want any type of authentication. 

V3 and V4 appear have a much more strict definition of what "anonymous" means, so how do I make this new version functionally equivalent to V2?

**Comment by pacaj2am** [comment]
Hi, seems  `"anonymous": true,` works, if you see: `ACL denying access to client with dangerous client id "mosqsub/13224-subsonic"` it is complainig about client id, where should be no slash.

**Comment by riston** [comment]
Yes changing `"anonymous": true` works, but what would be a proper fix to change the client id naming schema?

**Comment by marc-gist** [comment]
Anonymous still looks to be non-functioning :(

**Comment by joekob** [comment]
Hi marc-gist,
I have the same issue, that my anonymous logins to mosquitto server are not working. Did you find some solution for you issue?
BR, Joe
