### ISSUE TITLE
"Start on boot" does not work for custom_deps

### ISSUE THREAD

**Issue by jumpkick** [home-assistant/hassio-addons#469]
Steps to reproduce:

* rm -rf /config/deps/* # empty config/deps
* Set custom_deps addon to "start on boot"
* Populate some pypi package to install (i.e. "networkx")
* Restart Home Assistant
* custom_deps container is not observed to start-up when the home-assistant container is restarted
* check /config/deps/ # empty

If one manually starts the custom_deps addon, the pypi packages are installed to /config/deps...

**Comment by frenck** [comment]
Hi there,

This is actually by design:

https://github.com/home-assistant/hassio-addons/blob/master/custom_deps/config.json#L7

Reasoning:
You can actually delete the deps folder and restart Home Assistant... 
In that case, it isn't Hass.io restarting, so even when your suggestion was possible, it would still not have been triggered.
