### ISSUE TITLE
/dev/serial/by-id doesn't work

### ISSUE THREAD

**Issue by hmorkemo** [home-assistant/hassio-addons#781]
I have my ConBee at /dev/ttyUSB1.
To avoid problems with the everchanging usb port numbers after rebooting my Intel NUC/Debian stretch, I tried to set
device="/dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DO00K8EX-if00-port0"
This causes an error when I restart deCONZ (version 237):
FATAL: No device /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DO00K8EX-if00-port0 found!

**Comment by pvizeli** [comment]
You need rerun the installer of Hass.io - I think you run a old version. On restart of device you should see an error on Hass.io logs that permission are not correct setup.

**Comment by hmorkemo** [comment]
How do I find out which version I have, and how do I run the new one? rerunning the installer sounds a bit risky... Isn't this taken care of by the version updating (I'm on 0.100.2 of ha).

**Comment by hmorkemo** [comment]
In my home-assistant log file I get this:
`19-10-14 14:37:01 INFO (SyncWorker_7) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-deconz with version 3.6
19-10-14 14:37:08 WARNING (MainThread) [hassio.api.security] No API token provided for /api/config
19-10-14 14:37:21 WARNING (MainThread) [hassio.api.security] No API token provided for /api/config`
4 times. Is because of the same thing?

**Comment by pvizeli** [comment]
That will be only shown on a full restart. You can rerun the scripts without running into an issue or update the script manual: https://github.com/home-assistant/hassio-installer/blob/master/files/hassio-supervisor but make sure that you replace the variables correct. It is important that the supervisor run with privileged.

**Comment by KennethLavrsen** [comment]
@pvizeli 

A gentle reminder

It smells like something we have seen quite many times before

https://github.com/home-assistant/hassio-addons/issues/685

https://github.com/home-assistant/hassio-addons/issues/689

https://community.home-assistant.io/t/deconz-official-thread/100504/577

https://community.home-assistant.io/t/usb-connection-problems-with-hass-io-on-intel-nuc-docker-and-ubuntu/147670

https://community.home-assistant.io/t/deconz-official-thread/100504/577

I no longer run the Deconz addon - I moved to bare metal installation because of this and I am happy to stay that way. But my personal theory is that the issue is the changes made in how udev is run when the addon is started. I think the new way does not execute udev in a way that is blocking which is why you had to add the fixed delay. But the fixed delay is not long enough if you happen to have a different USB device that does not finish its init within the waiting time. You should try to change the fixed delay by code that waits for udev to complete its tasks. And you probably cannot reproduce it because you do not have a 2nd USB device that starts slowly like an Aeotec.

If I am correct then the situation must be that... if the Conbee wakes up before the Aeotec, udev create the symlink in time for deconz to start and succeed. But if the Aeotec is first and takes its time, the Conbee stick does not get its symlinks created in time and the start script stops before deconz is started because your startup script checks for the device name from the config to be present and it fails when the by-id symlink is used in the config and udev has not had time to create it.

@hmorkemo what other USB device do you have besided the Conbee?
If you use the symlink in the Deconz addon config and remove the other USB device from the system, does the startup of the Deconz addon ever fail?

**Comment by filikun** [comment]
I have the same issue as well. This is my first time trying to boot up a Conbee 2 on Nuc, esxi, Hassio machine.

**Comment by pipovanpimperzele** [comment]
Same problem here. Just installed deconz addon 3.8. 
starting version 237

[15:47:33] FATAL: No device /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1996481-if00 found!

My setup:
Ubuntu LTS with:
arch | x86_64
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.4
timezone | Europe/Brussels
version | 0.102.3
virtualenv | false

**Comment by frenck** [comment]
I bet all these cases are due to an old startup script.
Please run the installer again to update this.

See our documentation:

<https://www.home-assistant.io/hassio/installation/#alternative-install-on-a-generic-linux-host>

You can run this on an existing system without issues. It will overwrite/update older scripts in the process.

**Comment by KennethLavrsen** [comment]
I did that twice @frenck 
It made no difference. I found that in my installation it fails because I have two USB devices. The Conbee II and the Aeotec zwave stick. And it points to the problem that if udev detects the Aeotec first it does not finish creating the symlink for the Conbee within the 5 seconds timeout that is in the startup script of the Addon, then startup script terminates. All these problems started when the Addon was changed so it runs udev in a different way. And with this change the developer added the 5 second delay that was not there before. I guess the new way to run udev is not blocking. It does not wait till udev is done.  I did know how to change the run script inside the docker container so I gave up and installed deconz on bare metal. 

If you want to make an attempt to fix this then I would change the run script so it waits for udev to complete instead of waiting fixed 5 seconds.  If you do not have two USB sticks that compete for the ttyACM name space, and your udev takes longer than 5 seconds to create the symlink, then you cannot reproduce it. It may also work by increasing the 5 second delay. But then how long? And why delay startup time for all that do not need it. Best is to wait with a long timeout before giving up

**Comment by frenck** [comment]
That I can work with.

**Comment by pipovanpimperzele** [comment]
Just tried the latest deconz version (3.9) but this did not solve my problem. 
After a timeout it says FATAL:  no device ...... found.

Now I did a recover from an earlier backup where deconz 3.1 was present and this version works without any problems. 

I am a bit scared to run the installer again. Now everything is working and for the moment I will stick to deconz 3.1

**Comment by frenck** [comment]
@pipovanpimperzele Don't worry about running the installer again. It installs the startup scripts.

Or, just take a snapshot before running it, it will act as an additional safeguard.

**Comment by pipovanpimperzele** [comment]
@frenck  
I am running Ubuntu + Docker ce on an intel nuc.
I have to do this (as root) to re-install?

curl -sL https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh | bash -s

**Comment by KennethLavrsen** [comment]
@pipovanpimperzele 
Maybe your problem is a different one than several of us had. You did not write about your config
- Do you have two USB devices that both get assigned device names /dev/ttyACM0 or 1?
- If yes, does the problem go away if you remove the other device and retry?
- If no, then you do not need to use the by-id link. If you only have one ttyACM0 device then just use /dev/ttyACM0

If it fails when you have only 1 USB serial device then you have a different problem than @frenck so quickly fixed

I ran the installer script several times and it does not overwrite any configs. It is safe to try

**Comment by pipovanpimperzele** [comment]
@KennethLavrsen 
You are right. I only have 1 USB device. 
I changed the device to /dev/ttyACM0 , upgraded to v3.9 and it is still working!
Thx for the advice.

@frenck 
Actually it is mentioned in the deconz addon webpage to use in case of hass.io:
-    "/dev/ttyUSB0"
-    "/dev/ttyAMA0"
-    "/dev/ttyACM0"

I followed the video from Drzzs where he is using the full Conbee USB device name. This was working in v3.1.
Maybe the documentation can be adapted NOT to use "/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1234567-if00" .

Thx

**Comment by KennethLavrsen** [comment]
The thing is - if you have multiple serial USB devices that are assigned as ttyACM0 and ttyACM1 then there is nothing that controls which one becomes what at boot time.
In my case about half of boots goes one way and half the other. And then both the deconz and zwave fails when the boot order by chance goes the other way.
This is where the by-id links helps us. At boot udev creates these symbolic links in a predictable way. When you start the deconz in docker, docker does not know these until a local docker container udev instance does the same and creates the symlinks.

The bug several of us saw was that when we started the Deconz addon, it died in many cases but also succeeded very often

Your case is very different

Where did you get the by-id link from? They are unique and depend on the serial number of the Conbee stick

**Comment by pvizeli** [comment]
> "/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1234567-if00"

Work only with a supervisor they run in a privileged mode for access to udev. Older installation before 1.5 years run with unprivileged mode and the device comes never up.

**Comment by KennethLavrsen** [comment]
@pvizeli thanks for following up. So there are two very different failure modes. The mode I reported and other also was that it "randomly" failed and that is the one that french fixed.
And the other mode is a matter of updating version. Is there a command line way to identify if it is the supervisor unpriviledged mode that is the problem? I ask to I can better help people when they report similar issues in future.

**Comment by Letalis** [comment]
I have just found this thread and reliazed that I have the same issue as KennethLavrsen mentions..

**Comment by KennethLavrsen** [comment]
I mention two problems.
Which one? 

You have two or one ttyACM devices that occationally swap between 0 and 1?
And the problem occurs randomly when restarting the deconz addon?
This I assume is fixed with latest version of deconz addon

The other problem that pvizeli refers to is that people with older hassio installations installed on a parent Linux may need to rerun the installer script to upgrade the supervisor code which probably does not get upgraded during normal hassio upgrades.

Two different issues with two different cures.

Can you try the two cures and report the result? If the cures do not work then we need a new bug report with more details than a mee too.

**Comment by Letalis** [comment]
Sorry, my bad.
It was the swapping error:
You have two or one ttyACM devices that occationally swap between 0 and 1?
And the problem occurs randomly when restarting the deconz addon?

it all started for me after upgrading to latest version of Deconz.

**Comment by pvizeli** [comment]
Yeah, to run the installer script again don't solve the issue directly. It solve it on next update. To force this:

```
systemd stop hassio-supervisor.service
docker rm -f hassio_supervisor
systemd start hassio-supervisor.service
```

**Comment by KennethLavrsen** [comment]
As I have said I moved over to running deconz on bare metal to avoid this problem

But I wanted to follow up to see if the two fixes in combination resolves the problem and if my theory of the 5 second delay was correct.

So I disabled my bare metal deconz and reinstalled the addon. And I also reran the hassio installer script. I ran the 3 commands pvizelli gave us.

And I setup deconz using the by-id link.

The result is - out of 10 restarts of the deconz addon - 1-2 fails. I tested 20 times and it failed to start 3 times.

The failure mode is the same as I observed in my original report. It fails right way with the log message

```
starting version 237

[13:39:01] FATAL: No device /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1962724-if00 found!
```

If it works it runs instantly. When it fails it fails after the new 60 second time out.

I had hoped the udev creation of the symlink just took longer than the 5 seconds. It cannot take more than 60 so it seems that it randomly just fails. And I have no clue how to debug that further.

In the bare metal Ubuntu there is never any problem with the by-id symlink. And the deconz app also worked until the udev code was changed. 

What was the reason for the original change? Any problem changing back to what it was?

**Comment by filikun** [comment]
On a fresh install today this error seems to be there.

**Comment by MTrab** [comment]
Never seemes like /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2141754-if00 is a working path :( That's a bummer, as ttyACM0 and ttyACM1 sometime swaps places.

I have tried running the script installer several times but always end up with the same error, deconz is hanging on startup and eventually fails connecting to the device.

Please fix this rather than closing every issue without a fix.
