### ISSUE TITLE
Samba Addon: Cannot connect using Hostname

### ISSUE THREAD

**Issue by voydz** [home-assistant/hassio-addons#796]
Hey there,

so I am using the Samba Addon v9.0 and I noticed a strange behavior. I can connect using the IP Address but not the hostname. This has already worked for me in the past. (Around v5 of the addon or sth like this)

The addon log entry after using the hostname looks like this:

```
Denied connection from ... (...)
Connection denied from ... to ...
```

I am using the current version of hass (0.100.2) with hassio (supervisor v189) on a Debian 10 VM.

**Comment by voydz** [comment]
So no advice or anything? Not even a workaround or someone who can explain what the cause might be?

**Comment by FlavorFx** [comment]
same issue on my mac and Windows PC.

**Comment by arthurkrupa** [comment]
Same issue on MacOS Catalina and HA (0.101.3).

- Samba works with Finder when using IP, but fails when trying to connect to the auto-discovered host (going to Network -> hassio produces "Connection error").
- Hostname works fine in browsers

**Comment by mattiev83** [comment]
I'm not good at explaining a lot (I tend to lack the patience for it), but here's what I did. I hope it helps you.

I tried to connect via file explorer, and was denied. Windows prompt gave no explanation, although there was a code (0x80070035). A quick Google search led my to this video: https://www.youtube.com/watch?v=YG3iND6Ts6k

I followed the instructions, but still nothing worked. I realized that the log file was showing an IPV6 denial, which is strange because we don't have IPV6 out where I live. I went back into my network and disabled IPV6, refreshed my desktop, and voila! I was able to connect. I'm still learning my way around this world, so this may or may not be the answer you are looking for, but if it is, I'm glad.

**Comment by FlavorFx** [comment]
For Mac, I found a work around but probably this will work for windows as well: First I changed my samba share config file. I changed "allow_hosts" to my specific IP6 address of my HassIO server. I found this address in my router. 

```
  "allow_hosts": [
    "::aaaa:bbbb:cccc:dddd"
  ],
```

After this I was able to connect. When I changed it back to my old configuration, it still works. 

```
  "allow_hosts": [
    "192.168.0.0/16"
  ],
```

This failure is related to IP6 address range...

**Comment by ozboss** [comment]
Can confirm this on Windows.
Not messing with IPV6, anyway the network doesn't show up by itselfe, \\HASSIO doesn't work either.
But I am able to access with \\ip.of.hassio.host

**Comment by Kodemikkel** [comment]
I now have the same problem after updating to Hass.io version 0.160.0.
"HOMEASSISTANT" was visible in the Network tab in file explorer before I updated, but not anymore. I can, however, access it in file explorer using the IP address.
The Samba log say: "Connection denied from ipv6:(ipv6 address of my computer)"
I can probably just set allowed hosts to allow that specific IPv6 address, but I find it weird that it worked before, but not anymore
