### ISSUE TITLE
Deconz: error APSDE-DATA.confirm: 0xA7 on task

### ISSUE THREAD

**Issue by jonskoglund** [home-assistant/hassio-addons#877]
I have a small Zigbee mesh (Deconz + ConbeeII) with a Hue light that is responding with a serious delay or not responding at all to changes by flipping switch in HA.
The Deconz log shows this:
```
13:54:22:018 device state timeout ignored in state 3
13:54:23:069 device state timeout ignored in state 3
13:54:25:770 device state timeout ignored in state 3
13:54:26:742 timeout on poll APS confirm
13:54:26:762 Current channel 25
13:54:26:772 Device TTL 4500 s flags: 0x7
13:54:27:114 0x0017880102372BAD error APSDE-DATA.confirm: 0xA7 on task
13:54:28:071 device state timeout ignored in state 3
13:54:36:242 device state timeout ignored in state 3
```
Deconz 3.9
ConbeeII FW 264A0700 2.05.71
Attached an image of the mesh.
![Screenshot 2019-12-06 at 15 04 35](https://user-images.githubusercontent.com/593324/70329261-47811380-183b-11ea-821c-b7e21f5cf88c.png)
Any tips on improving the performance of this mesh are also appreciated :-) 
When is a link between a node considered GOOD and when bad?

**Comment by frenck** [comment]
The link is green, so that seems good :) (it becomes lime/yellow/orange in case it becomes less good).

The main issue, is that this is the add-on. Add-ons wrap existing software.
Please report this issue upstream:

<https://github.com/dresden-elektronik/deconz-rest-plugin>

This part of the "software" stack is not created or maintained by us.
