### ISSUE TITLE
Homematic WebUI broken after update from 9.3 to 9.5

### ISSUE THREAD

**Issue by sbyx** [home-assistant/hassio-addons#925]
After upgrading from 9.3 to 9.5 the WebUI is not really accessible anymore for me. it seems that the lighttpd (reverse proxy?) config got screwed somehow internally after the recent changes from @pvizeli Here some log excerpt:
```
2019-12-20 09:47:17: (configfile.c.1367) include file not found:  /etc/lighttpd/conf.d/sslsettings.conf 
2019-12-20 09:47:17: (configfile.c.1289) source: /opt/hm/etc/lighttpd/conf.d/proxy.conf line: 33 pos: 3 parser failed somehow near here: (EOL) 
2019-12-20 09:47:17: (configfile.c.1289) source: /opt/hm/etc/lighttpd/modules.conf line: 150 pos: 8 parser failed somehow near here: (EOL) 
2019-12-20 09:47:17: (configfile.c.1289) source: /opt/hm/etc/lighttpd/lighttpd.conf line: 88 pos: 12 parser failed somehow near here: (EOL) 
lighttpd-angel.c.148: child (pid=191) exited normally with exitcode: 255
```

Also my addon config for reference:
```
{
  "rf_enable": false,
  "rf": [
    {
      "type": "CCU2",
      "device": "/dev/ttyAMA0"
    }
  ],
  "wired_enable": false,
  "wired": [
    {
      "serial": "xy",
      "key": "abc",
      "ip": "192.168.0.0"
    }
  ],
  "hmip_enable": true,
  "hmip": [
    {
      "type": "HMIP_CCU2",
      "device": "/dev/ttyUSB0"
    }
  ]
}
```

**Comment by hannes2323** [comment]
I can confirm the exact same problem on my side. 

Communication from HA to the HomeMatic devices still does work, but webinterface is not accessible (in fact, port 80 is not bound to any service) and HA can not read values from HomeMatic devices.

This is a major problem, please have a look.

Thank you!

**Comment by pvizeli** [comment]
It is fixed with 9.6. I moved back to origin ReGaHss. Be careful that the WebUI is still only to manage/add devices.

We move this to ingress, but the progress is slow because I have no one they help me to maintain this add-on.

**Comment by sbyx** [comment]
Thanks for the quick support and all the efforts on the addon. I'm still a bit inexperienced with homematic but I wanted to have a look into debmatic a bit more. Would this potentially be a an option to ease the maintenance effort since everything is nicely packaged as .deb?

**Comment by pvizeli** [comment]
the issue is that there exists no documentation and every maintainer of a kind of CCU does it differently. The biggest issue, it's not a software, is a toolset of hacks, scripts, binary and systemV runners. The difficulty is to run CCU as a service like we did and not as the full and only solution.

debmatic have the same issue, it needs systemd to run that million of scripts for the CCU and that is nothing that will work on a container.

XMLRPC works fine, that ReGaHss also works fine, we need patches for TCL/HTML/JS to work on hour solution like i.e. Raspberrymatic does because of the vanilla ReGaHss.

Or short,  if someone will rewrite the HTML and TCL to remove all the functions they do not work inside container, everything is fine.

For now, every time if an update is out we look at https://github.com/jens-maus/occu and what the update needs on filesystem with RaspberryMatic and adapt this if it is also needed on a container.

**Comment by koslo** [comment]
I updated to 9.6 and got another error:
`/opt/hm/bin/tclsh: /lib/i386-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/hm/lib/libtcl8.2.so)`

**Comment by sbyx** [comment]
Closing this since original issue is resolved I guess.
