### ISSUE TITLE
deconz - No direct access since ingress (4.0)

### ISSUE THREAD

**Issue by Cuthbert1337** [home-assistant/hassio-addons#926]
I often used direct access to the deconz addon as a quick and comfortable option to see and configure my zigbee devices. For example adding a new device....

Now that is pretty uncomfortable especially on smartphone.

I'd really like to see port forwarding of the internal http-ports again. Otherwise I'd have to run a deconz container standalone.

**Comment by frenck** [comment]
Even with Ingress that will still work (just tested it myself on my iPhone). Suggestion: Add it to the sidebar by toggling the "Show in sidebar" feature.

We can't offer Ingress and Direct access at the same time for deCONZ since it causes issues with the discovery feature inside Phoscon itself. So, unfortunately, enabling/restoring that functionality is not an option.

**Comment by mickeman** [comment]
Is there any way to access the deconz api after this change?

**Comment by pvizeli** [comment]
You can use the Home Assistant API that handle the deconz API

**Comment by mickeman** [comment]
I´m trying to get the Hue essentials app that were working from my phone with direct access to deconz before to work, is that still possible?

**Comment by Tickaren** [comment]
I cant access the "Old WebApp version" through ingress.. I get a 404..
