### ISSUE TITLE
DeCONZ update to 4.1 make impossible to open the old application

### ISSUE THREAD

**Issue by lbouriez** [home-assistant/hassio-addons#936]
Hello, since the last update and the implementation of Ingress I can't log into the old app.
After clicking on the link, I quickly see the old app and then I am being redirected to `https://ha.bouriez.org/pwa/login.html`

**Comment by thaefner** [comment]
@lbouriez DeConz now uses Ingress, so it is only available over the Interface of Home Assistant.

Even there, over Ingress, I can not access the Phoscon Web-Interface. But my Devices work in HA, so the API seems to be accessable. The Gateway also shows up with the IP 172.30.33.0 which is defnitly wrong. I also think my Conbee II is still on 2.5.71? I am using HassOS.

**Comment by bratanon** [comment]
Disable the IP ban in the "http" config or else you will not be able to login.

**Comment by lbouriez** [comment]
> Disable the IP ban in the "http" config or else you will not be able to login.

I tried but I am still redirected to this page `https://ha.bouriez.org/pwa/login.html` whit `404: Not Found` as content

**Comment by SiliconAvatar** [comment]
After removing IP Ban, restart HA. Then clear your browser cache and try again, or try on a completely different browser/computer.

**Comment by thaefner** [comment]
Is IP Ban not disabled by default? It says so in the Doku:
https://www.home-assistant.io/integrations/http

**Comment by frenck** [comment]
The old web UI (as in, before the PWA), isn't available at this point and technically can't be made available right now as well.

Everything else is documented now in #939 

Not sure how people bring in the IP banning since that was in no way related to your initial question.

**Comment by lbouriez** [comment]
> The old web UI (as in, before the PWA), isn't available at this point and technically can't be made available right now as well.
> 

Ok, thanks, I thought it was an issue.

**Comment by ohjohnsen** [comment]
@frenck What is the status on this issue as of now?  Earlier I ran deCONZ using a Docker container, and then I used the old interface to create switch "groups" for my Trådfri remote controls.  This way it's possible to link the remote to Ikea bulbs so that they could be controlled even if deCONZ is down.  Anyhow, using the old interface is the only way I've been able to add the switch "groups".  
![image](https://user-images.githubusercontent.com/16133835/114285636-031e0d00-9a59-11eb-9159-29d32f3d3b1a.png)
