### ISSUE TITLE
hassio-addons/check_config/ does not show the full log when error is encountered

### ISSUE THREAD

**Issue by TexasGrill** [home-assistant/hassio-addons#964]
Per this thread I am opening an issue with check_config addon.   
https://community.home-assistant.io/t/i-want-to-upgrade-but-the-ha-config-checker-scares-me/157542/8

OP, you should report this as a bug, seems that your error message is so long that it’s only showing the end of it, which is no use as it is the start of it that we need.

Here's the log:
CHAC Utility Log:
https://paste.ubuntu.com/p/kKcrFS2Xcq/

**Comment by apop880** [comment]
I have the same issue. Tried running the config check add-on today against .105.1 and it errored but the log wrapped so I'm not sure what the actual error is. But I'm not comfortable upgrading in the meantime. Can the add-on be reconfigured to optionally pipe the log to a file?

**Comment by apop880** [comment]
Just following up to say that I was able to piece together where the issue was in my config and get it to process through the add-on successfully. But it would definitely be more intuitive if the whole log was available.

**Comment by skeptizzle** [comment]
@apop880 how did you do that? I'm in the same situation..

**Comment by apop880** [comment]
@skeptizzle At least in my case, I was able to piece together where in my configuration file the checker stopped processing, and it wasn't too far down. And I was only upgrading from .104 so there weren't a ton of possibilities to go back and look through in terms of breaking changes. Based on that, in my case, I was able to determine that the problem was with the Google Assistant integration; I was using the `api_key` and that was deprecated in .105 in favor of a `service_account` only.

**Comment by Rick-Git** [comment]
I guess I'm having the same issue. 
I'm on 104.2, trying to update to 106.5, 105.5 before. 
When running it just shows https://pastebin.com/QFp01Hru 

Did try to track the breaking changes, but it was still the same outcome

**Comment by apop880** [comment]
@Rick-Git are you able to share your whole config file? I'd be willing to take a look through it and see if I can spot the error.

I will say, once you get to 105+, this won't really be an issue any longer because of the addition of Safe Mode. I didn't even bother running the Check Config add-on when I upgraded from 105 to 106, since I knew I'd get dropped into Safe Mode if there were any issues with my configuration on the new release.

In fact, I wouldn't be surprised if this add-on gets deprecated somewhere down the line.

**Comment by Rick-Git** [comment]
@apop880 
It's a lot of work and files, I just shared my GitHub config.
Never placed one on GitHub, keeping my own back-ups safe. But this seems to be the easy way to share it with you. 
Hope you can help me! thanks!

**Comment by apop880** [comment]
@Rick-Git I dug around the docs a bit and it looks like `samsung_tv` is no longer a valid value in the `discovery` integration as of .105. Try removing that line and see if it validates.

**Comment by Rick-Git** [comment]
@apop880 you're my hero!!!! Changed it, runned it. No errors.
Thank you, thank you, thank you.

**Comment by nacbooth** [comment]
I'm continuing to find the abbreviated log snippet frustrating.  I makes finding the actual error exceptionally difficult.  I note the comment about the new safe mode, but I shouldn't have to start HA when I know there is a potential error.  TBH I'm not confident that this will be as reliable as it ought and I DREAD the time when I have to rebuild from scratch.

Please, please, can we have the full output somewhere - even if as a file to pull off the host?

**Comment by mikeybeck** [comment]
I'm running hassio and was able to view the full log by running `docker logs addon_core_check_config`.

**Comment by BGFHA** [comment]
> I'm running hassio and was able to view the full log by running `docker logs addon_core_check_config`.

Can you tell me where you are running that?

-----
To the developers:
Is there no possibility to change the log window at the bottom of the add-on so that it scrolls? This is a really useful add-on, but I find it frustrating having to run it multiple times in order to see the outcome of the check!

**Comment by mikeybeck** [comment]
@BGFHA I'm running it inside the directory where hassio is installed.
I'm pretty sure you should be able to run it anywhere the `docker` command is available.
